export * from './academicDepartment.interface';
export * from './academicFaculty.interface';
export * from './academicSemester.interface';
export * from './admin.interface';
export * from './faculty.interface';
export * from './global.interface';
export * from './routes.interface';
export * from './student.interface';
export * from './user.interface';
